### ISSUE TITLE
hdfscli download to stdout fails on python 3.6 with TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by thunderstumpges** [mtth/hdfs#100]
when using the command line hdfscli to download a file to stdout (in my case it was a text file, but would be nice to be able to download a binary file to stdout as well) I get 

      File "/usr/local/lib/python3.6/site-packages/hdfs/__main__.py", line 219, in main
        sys.stdout.write(chunk)
    TypeError: write() argument must be str, not bytes```

From this page: https://stackoverflow.com/questions/908331/how-to-write-binary-data-in-stdout-in-python-3

They suggest using `sys.stdout.buffer.write()` instead of just `sys.stdout.write()`. Indeed when I make this one line change, I can download my file to stdout.

Would this be an acceptable fix?
Thanks!

**Comment by thunderstumpges** [comment]
It looks like this is only for 3.x. In 2.x the code already present is probably right. What versions need to be supported? I think the two forms of writing could be conditional on `sys.version_info.major == 3` ?

**Comment by mtth** [comment]
Apologies for the slow reply; yes, we should support Python 2 and 3.

**Comment by mtth** [comment]
Fixed in `2.3.1`.
