### ISSUE TITLE
Network proxy support

### ISSUE THREAD

**Issue by shyam334** [mtth/hdfs#107]
Hello,
I was wondering if there is a way to specify a (network) proxy.
(quickly looked through the code and couldn't find a way to specify the proxies to the `Request` api)
Requesting the feature, if don't have it already.

Context: I cannot access HDFS NN directly from my machine, I have to use a proxy. (socks)

**Comment by mtth** [comment]
Hey. The `Client` [constructor](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client) accepts a `session` option which should let you do what you want (for example via the session's [`proxies`](http://docs.python-requests.org/en/latest/api/#requests.Session.proxies) field).

**Comment by shyam334** [comment]
I guess I didn't look hard enough. (Perhaps I'll add a line in docs sometime, which will help lazy folks like me)
Thank you.
