### ISSUE TITLE
a memory leak problem when using multi-threaded download/upload

### ISSUE THREAD

**Issue by tiraffe** [mtth/hdfs#108]
I found a memory leak problem when using this library (Python 3.6).
This problem occurs when you use multi-threaded download/upload multiple times.

After investigation, I found it was caused by the following code.
https://github.com/mtth/hdfs/blob/d0403b02d3114c62c35f87ac653a731de30d8060/hdfs/client.py#L1113-L1130

This memory leak problem can be reproduced by the following code:
``` python 
import os
import gc
import psutil

process = psutil.Process(os.getpid())
print(process.memory_info().rss)  # in bytes


for i in range(10):
    res = _map_async(4, lambda x:x+1, [1,2,3,4])

    gc.collect()
    process = psutil.Process(os.getpid())
    print(process.memory_info().rss)  # in bytes

```
I have created a PR to fix it: https://github.com/mtth/hdfs/pull/109
If I am mistaken, please let me know.

**Comment by mtth** [comment]
Thanks for the report @tiraffe. It indeed looks like `ThreadPool`s [don't get GC'ed](https://stackoverflow.com/a/47683305/1062617) automatically. I will merge your PR shortly.
