### ISSUE TITLE
 HdfsError: java.util.concurrent.TimeoutException: Idle timeout expired: 1000/1000 ms`

### ISSUE THREAD

**Issue by xmnlab** [mtth/hdfs#113]
hey everyone!

There is a issue on Ibis project related to hdfs (https://github.com/ibis-project/ibis/issues/1697).

The error message is this below:

```
...

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/ibis/filesystems.py in put(self, hdfs_path, resource, overwrite, verbose, **kwargs)
318 hdfs_path = self.client.resolve(hdfs_path)
319 self.client.write(hdfs_path, data=resource, overwrite=overwrite,
--> 320 **kwargs)
321 return hdfs_path
322

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hdfs/client.py in write(self, hdfs_path, data, overwrite, permission, blocksize, replication, buffersize, append, encoding)
474 return AsyncWriter(consumer)
475 else:
--> 476 consumer(data)
477
478 def upload(self, hdfs_path, local_path, n_threads=1, temp_dir=None,

~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hdfs/client.py in consumer(_data)
469 )
470 if not res:
--> 471 raise _to_error(res)
472
473 if data is None:

HdfsError: java.util.concurrent.TimeoutException: Idle timeout expired: 1000/1000 ms`

```
The error `HdfsError: java.util.concurrent.TimeoutException: Idle timeout expired: 1000/1000 ms` looks like it could be a Java problem related to Java timeout. 

it seems `timeout` specified on `request` is in `second`. In the example on https://github.com/ibis-project/ibis/issues/1697 the user specify `timeout=10000` so not sure why java is using timeout `1000 ms`.

any idea why this problem happens? thanks!

**Comment by mtth** [comment]
Hey @xmnlab. This timeout looks internal to HDFS; unfortunately the [WebHDFS API](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html) doesn't let us control it AFAICT (the `Client`'s `timeout` parameter is used by [`requests`](http://docs.python-requests.org/en/master/) and likely ignored by the server). It's hard to say more without a full stack trace of the timeout error. Consider filing an issue with the Hadoop folk.

**Comment by xmnlab** [comment]
@mtth thanks! I will do it!

**Comment by mtth** [comment]
Any updates @xmnlab?

**Comment by xmnlab** [comment]
@mtth I needed to stop the investigation, sorry. I am going to restart this task this week and I will let you know the updates. thanks!

**Comment by mtth** [comment]
Closing since it looks unlikely we should do something on the HdfsCLI side; feel free to reopen if you think otherwise.

**Comment by bdiiot** [comment]
HttpFS:14000 ?
hadoop.http.idle_timeout.ms
https://hadoop.apache.org/docs/stable/hadoop-hdfs-httpfs/httpfs-default.html
