### ISSUE TITLE
Walk the path when the directories under the path change

### ISSUE THREAD

**Issue by darouwan** [mtth/hdfs#114]
When I try to walk a specified path, some dirs under the path may deleted,  which causes 'HdfsError: File does not exist' error. 
Actually I think this error can be skipped and ignored. Is any good idea to solve this problem?

**Comment by Tanmoy248** [comment]
What is your use-case? Can you please explain more about your implementation scenario

**Comment by darouwan** [comment]
Hi @Tanmoy248 
The usecase is, when I walk a path where some directories under this path is changed or deleted, it will the generator throws an exception and stops. Actually I needn't to care about these modified directories, just want to skip it and continue the walk path generator.

**Comment by mtth** [comment]
Starting version `2.3.0`, [`client#walk`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.walk) supports an `ignore_missing` option which should satisfy your use-case.

**Comment by darouwan** [comment]
Thanks a lot!
