### ISSUE TITLE
package is not published on conda...

### ISSUE THREAD

**Issue by petacube** [mtth/hdfs#116]
any plans?

**Comment by mtth** [comment]
No plans so far, help is welcome :).

**Comment by ericdill** [comment]
This package is available on conda-forge. [Here's the feedstock.](https://github.com/conda-forge/python-hdfs-feedstock). You can install it via `conda install -c conda-forge python-hdfs`

**Comment by mtth** [comment]
Thanks @ericdill! I've included a link to the feedstock in the README.
