### ISSUE TITLE
KerberosClient does not support verify and cert

### ISSUE THREAD

**Issue by tritab** [mtth/hdfs#117]
Thanks for such a useful package. I ran into the same problem as https://github.com/mtth/hdfs/issues/79. I believe the KerberosClient suffers from the same issue as https://github.com/mtth/hdfs/issues/22 since verify and cert aren't passed to the request object. I did some local testing and was able to get verify to work by adding it to the session https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L121 

This might be a useful addition for users who have a cluster using both Kerberos and SSL.

**Comment by mtth** [comment]
Hi @tritab, can you clarify which feature isn't currently supported? `KerberosClient`'s (as well as other clients') constructor already allows passing in a session object directly, on which you can specify `verify` and `cert` options IIRC.

**Comment by mafeko** [comment]
I was looking into this as well. Thanks @mtth for this great package and the quick response time. For me this seems solved.

**Comment by tritab** [comment]
Thank you for taking a look at pointing me in the right direction. I was able to get the following to work:

```
os.environ['REQUESTS_CA_BUNDLE'] = '/path/to/certs.pem'
session = Session()
client = KerberosClient('https://host:14000', session)
```
