### ISSUE TITLE
How to set replication factor of a directory?

### ISSUE THREAD

**Issue by darouwan** [mtth/hdfs#118]
I found in current set_replication method:

>  hdfs_path – Path to an existing remote file. An HdfsError will be raised if the path doesn’t exist or points to a directory.

Where the hdfs path cannot be a directory. 
Even though I can do with it via hdfs_client.walk() firstly, I need to request for each file and  consume a lot of http connections. 
Any good solution for change the replication factor for a directory?

**Comment by mtth** [comment]
Unfortunately it doesn't look like the underlying filesystem supports setting replication for a directory (the [method](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/fs/FileSystem.html#setReplication(org.apache.hadoop.fs.Path,%20short)) only accepts files). We could add logic on our side to pretend it does but it might not provide the right incentives: increasing replication is expensive even for a file, potentially copying large quantities of data.

It seems reasonable to walk the directory first. This requires one extra request per directory which should be fine unless you are changing a very deep tree (it would still be just one connection overall: `hdfs` clients actually reuse these).

**Comment by darouwan** [comment]
But the command 'hadoop fs -setrep 1 /' can support the directory. As hdfs java api support file only, it may be implemented by other way?

Actually I want to decrease the replication number..
