### ISSUE TITLE
Can't set timeout for requests

### ISSUE THREAD

**Issue by forsberg** [mtth/hdfs#12]
Evaluating this package. Looks good, but I would like to be able to set timeouts when making requests to cope better with any namenode/datanode hickups.

Can't figure out how to do that easily. Is there a way?

**Comment by mtth** [comment]
There's no exposed way of doing this currently but I can look into adding it.

Which level of granularity would suit your use-case (e.g. is a client-wide setting enough or do you expect to want different timeouts for `read` v.s. `status` calls)?

**Comment by forsberg** [comment]
A client-wide setting is enough, and I think what would make most sense is that you set something that is passed directly as timeout to the request call, i.e. something that can be either a float to make it both connect and read timeout, or a tuple with connect and read timeout.

My use case is that I have a daemon with worker processes, and one of the things these worker processes do is to upload some data to HDFS. If that hangs, it's better that I notice and retry later than get a hanging worker process.

**Comment by mtth** [comment]
Feature added in c091c06 (version `>=0.5.0`).

The `Client` constructor now takes an additional `timeout` keyword argument that will be used for all requests emitted. Format is what you mention (i.e. the same as `request`'s). If you want to get fancy, the attribute is also available directly on the client!
