### ISSUE TITLE
timeout value is still too large in windows 64bit os 

### ISSUE THREAD

**Issue by debuggy** [mtth/hdfs#123]
When using hdfscli download a folder to local, there will be a OverflowError same as #94 :
```bash
OverflowError: timeout value is too large
```

This is because threading.TIMEOUT_MAX is much smaller in windows than in linux. If I change the   [the number of this line]( https://github.com/mtth/hdfs/blob/28e42b3a050abe67d31704177292d4822aa152c1/hdfs/client.py#L1167) to:
```python
results = pool.map_async(func, args).get(4294965)
```
The Error will be fixed. So could the timeout value be changed smaller for windows system?

on windows:
![threading.TIMEOUT_MAX in windows](https://user-images.githubusercontent.com/8444268/56880661-38113f00-6a90-11e9-9add-5ebe3aadae06.png)
on linux:
![threading.TIMEOUT_MAX in linux](https://user-images.githubusercontent.com/8444268/56880658-35aee500-6a90-11e9-944b-557e86d840ae.png)

**Comment by mtth** [comment]
Fixed and released in `2.5.2`!
