### ISSUE TITLE
reading json file

### ISSUE THREAD

**Issue by mdumer** [mtth/hdfs#124]
Hi,
Hope you are doing well.
i am trying to read from HDFS but i am getting an error from it. 

Code:

from hdfs.client import Client
cl = Client("http://111.111.1.1:50070")
with cl.read('/user/abc.json', encoding='utf-8') as reader:
    import json as js
    model = js.load(reader)

Error:
HTTPConnectionPool(host='hdp-slave1.com', port=50075): Max retries exceeded with url: /webhdfs/v1/user/abc.json?op=OPEN&namenoderpcaddress=hdp-master.com:8020&offset=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BB98ED34A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Thanks

**Comment by mtth** [comment]
This looks like a connection issue; are you able to read other files on the cluster or access it with other means? You also are using the base `Client` which doesn't have any authentication built-in and is usually insufficient, depending on your cluster setup you might want to switch to an [`InsecureClient`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.InsecureClient), [`TokenClient`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.TokenClient), or [`KerberosClient`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.ext.kerberos.KerberosClient) for example.
