### ISSUE TITLE
Unicode Characters in Java Exception causes UnicodeEncodeError.

### ISSUE THREAD

**Issue by mattjsmithson** [mtth/hdfs#127]
Hi.

When using the hdfs API to transfer a file with an extended character in it's name the transfer fails with: 
 File "/usr/local/lib/python2.6/dist-packages/hdfs/client.py", line 539, in upload
    message = str(err)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 20: ordinal not in range(128)

The application is uploading a file called homé.txt to a path of /containers/homé.txt

I've fixed it locally by changing the **message = str(err)** call to encode the err string but the characters are lost.

I believe the issue is caused by the Java exception thrown after checking if the path exists containing the Unicode character.

Cheers,

Matt

**Comment by mtth** [comment]
Should be fixed in `2.5.3`. Please reopen if not.
