### ISSUE TITLE
Does hdfs require pandas==0.14.1 or pandas>=0.14.1 ?

### ISSUE THREAD

**Issue by laserson** [mtth/hdfs#13]
pip-installing hdfs uninstalled my newer pandas.

**Comment by mtth** [comment]
Seems to work for the current version as well (`0.16.0`), so changed the requirement to a lower bound in d399ccfef587280e4964550afe680268292d9ed5. Let me know if you run into any other issues.

**Comment by laserson** [comment]
thx!
