### ISSUE TITLE
Call to InscecureClient upload never returns

### ISSUE THREAD

**Issue by lochbrunner** [mtth/hdfs#131]
As the title states:

```python
from hdfs import InsecureClient

params = {
    'local_path': '~/test.txt',
    'hdfs_path': '/data/text.txt',
    'overwrite': True
}

client = InsecureClient( 'http://namenode:50070', user='me')
client.upload(**params)
```

The last call does never return while the file to upload is very tiny.

**Comment by mtth** [comment]
Can you run the script with logging enabled and share the output here? For example, you can add the following lines at the top:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by lochbrunner** [comment]
Might the proxy cause this problem?
Other tasks as `list` work fine.

> INFO:hdfs.client:Listing '/data'.
DEBUG:hdfs.client:Resolved path '/data' to '/data'.
DEBUG:hdfs.client:Resolved path '/data' to '/data'.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:3128
DEBUG:urllib3.connectionpool:http://127.0.0.1:3128 "GET http://namenode:50070/webhdfs/v1/data?user.name=me&op=LISTSTATUS HTTP/1.1" 200 None
DEBUG:hdfs.client:Upload destination '/data/test.txt' already exists. Using temporary path '/data/test.txt.temp-1560524662581941'.
DEBUG:hdfs.client:Uploading 1 files using 1 thread(s).
DEBUG:hdfs.client:Uploading '~/test.txt' to '/data/test.txt.temp-1560524662581941'.
INFO:hdfs.client:Writing to '/data/test.txt.temp-1560524662581941'.
DEBUG:hdfs.client:Resolved path '/data/test.txt.temp-1560524662581941' to '/data/test.txt.temp-1560524662581941'.
DEBUG:urllib3.connectionpool:http://127.0.0.1:3128 "PUT http://namenode:50070/webhdfs/v1/data/test.txt.temp-1560524662581941?user.name=me&overwrite=True&op=CREATE HTTP/1.1" 307 0

**Comment by mtth** [comment]
> Might the proxy cause this problem?

It's almost certainly a network issue. WebHDFS write requests have to talk directly to the DataNodes (more information [here](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#CREATE)), while most others only talk to the NameNode. You probably don't have access to the DataNodes.

Do you know if [HttpFS](https://hadoop.apache.org/docs/r2.4.1/hadoop-hdfs-httpfs/index.html) is enabled in your cluster? If so, you can just switch the URL in your client to the HttpFS port and everything should work (the API is the same and all requests would go through the HttpFS server).
