### ISSUE TITLE
upload error handler

### ISSUE THREAD

**Issue by vinsia** [mtth/hdfs#134]
upload will ignore exceptions when nThread is greater than 1. cause exception handler can't catch exceptions from sub-thread.
we need to fix this.

**Comment by vinsia** [comment]
@mtth

**Comment by mtth** [comment]
Can you clarify what you mean? In particular why the [existing handler](https://github.com/mtth/hdfs/blob/c9e032adf83fdad78f7b7aab77f2928c6a27dce3/hdfs/client.py#L603) isn't sufficient.

**Comment by vinsia** [comment]
you are not able to catch error raised by _map_async. cause the exception is from other thread.

**Comment by mtth** [comment]
Can you share a snippet reproducing the behavior? AFAIK calling [`get`](https://github.com/mtth/hdfs/blob/c9e032adf83fdad78f7b7aab77f2928c6a27dce3/hdfs/client.py#L1184) on a `map_async`'s result will do the right thing w.r.t. exceptions in child threads (reraising the first one and killing the other threads).
