### ISSUE TITLE
Authentication failure. Check your credentials

### ISSUE THREAD

**Issue by ookk** [mtth/hdfs#137]
mycode:
from hdfs.client import Client
client = Client("http://ip:port")
client.list("/")

when run, the error code is following:
HdfsError('Authentication failure. Check your credentials.')

**Comment by ookk** [comment]
the additional log:
ERROR:hdfs.client:<html><head><title>Apache Tomcat/6.0.48 - Error report</title><style></style> </head><body><h1>HTTP Status 401 - Authentication required</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Authentication required</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.48</h3></body></html>
Traceback (most recent call last):

**Comment by mtth** [comment]
It looks like your HDFS cluster expects requests to be authenticated. You'll need to use the appropriate client, for example a [`KerberosClient`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.ext.kerberos.KerberosClient) or a [custom secure client](https://hdfscli.readthedocs.io/en/latest/advanced.html#custom-client-support).
