### ISSUE TITLE
Writing to file-like object fails

### ISSUE THREAD

**Issue by chrisfontana** [mtth/hdfs#139]
Writing to the file-like object provided by the `hdfs.client.Client.write` method fails. 

`  File ".../python3.7/site-packages/hdfs/util.py", line 104, in __exit__
    raise self._err # pylint: disable=raising-bad-type
  File ".../python3.7/site-packages/hdfs/util.py", line 76, in consumer
    self._consumer(data)
  File ".../python3.7/site-packages/hdfs/client.py", line 472, in consumer
    raise _to_error(res)
hdfs.util.HdfsError: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>411 Length Required</title>\n</head><body>\n<h1>Length Required</h1>\n<p>A request of the requested method PUT requires a valid Content-length.<br />\n</p>\n</body></html>\n'`

I tested using the sample code provided in the write method documentation:
records = [
        {'name': 'foo', 'weight': 1},
        {'name': 'bar', 'weight': 2},
]

# As a context manager:
with client.write('/tmp/records123', encoding='utf-8') as writer:
    dump(records, writer)

I tested using release 2.5.8 on Python 3.7.0.

**Comment by mtth** [comment]
Which version of Hadoop is your cluster running? Are you using WebHDFS or HttpFS?

**Comment by HaoXuan40404** [comment]
I have same problem too, my client can use namenode(like mkdir or ls), but cannot use datanode,(like download or upload), my network work right

**Comment by HaoXuan40404** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/34049754/165458726-f80fc15f-eecb-470b-a58e-44bb458b27e8.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/34049754/165458745-c117d873-1115-4b78-824b-0395650a03c0.png">

**Comment by HaoXuan40404** [comment]
> 

```python

if __name__ == '__main__':
    hdfs_client = HdfsApi()
    local_path = "./test_data.csv"
    print(hdfs_client.client.list('/'))
    print(hdfs_client.client.list('/ppc'))
    hdfs_path = "/root/LICENSE.txt"
    hdfs_client.get_dataset(hdfs_path, local_path)
```
