### ISSUE TITLE
Expose a listdir method

### ISSUE THREAD

**Issue by laserson** [mtth/hdfs#14]
The only way to get a directory listing is to use the internal API like so

```python
client._list_status(path).json()
```

It'd be great to have a `client.listdir(path)` method.

**Comment by mtth** [comment]
You can use the [`walk`](http://hdfscli.readthedocs.org/en/latest/api.html#hdfs.client.Client.walk) function for that.

E.g. if you only want a list of statuses (similar to what your example seems to do):
```python
statuses = [status for _, status in client.walk(path, depth=1)][1:]
```
This way it's also straightforward to get a dictionary keyed by path of statuses (will also include the containing directory):
```python
statuses = dict(client.walk(path, depth=1))
```

Does this address your use-case?

**Comment by laserson** [comment]
It certainly addresses the problem, but I feel like listing a directory is a pretty common operation, and so doing

```python
list(client.walk(path, depth=1))[1:]
```

IMO seems more complicated than

```python
client.listdir(path)
```

especially since it's necessary to drop the first element of the list when using `walk()` (easy to forget to do that).

I believe `LISTSTATUS` is one of the core WebHDFS commands anyway, no?  Anyway, I'd still vote for a separate method for this particular use case.

**Comment by mtth** [comment]
Fair enough, this is pretty straightforward and the convenience is probably worth the extra code. 44aacf630c084b0b04fd05d281523c1e4d9a2fd9 adds a [`list`](http://hdfscli.readthedocs.org/en/latest/api.html#hdfs.client.Client.list) method to all clients (version `>= 0.5.2`)!

**Comment by laserson** [comment]
great, thanks @mtth!
