### ISSUE TITLE
Why is there no copy method

### ISSUE THREAD

**Issue by lblv** [mtth/hdfs#143]
Why is there no such command ？

hdfs dfs -cp /data/tmp  /bak/

**Comment by mtth** [comment]
AFAICT [WebHDFS](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html) does not have a native file copy method. This means that remote copies using the library will be inefficient (requiring transferring the entire data over and back). Until native support is introduced, I think it is best to avoid adding a first class command which would have surprising performance. The functionality is easy enough to reproduce using download and upload commands when performance is not an issue.
