### ISSUE TITLE
Where do I begin...

### ISSUE THREAD

**Issue by Slowly** [mtth/hdfs#144]
1. how to setup the configuration environment variable in windows
2. how to login without saving credentials in plain text
3. where is the rest of the api
.
.
.

**Comment by mtth** [comment]
I'm not sure what you mean by configuration environment variable (this library doesn't require any) or by the rest of the API. Have you read through [the quickstart guide](https://hdfscli.readthedocs.io/en/latest/quickstart.html)?

W.r.t. safe login, this will depend on how your cluster is set up. Most production clusters I am aware of use [Kerberos](https://web.mit.edu/kerberos/), and you would use a [`KerberosClient`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.ext.kerberos.KerberosClient) here which does not require a password.
