### ISSUE TITLE
[WinError 10060] Ocassional Timeout Error

### ISSUE THREAD

**Issue by Rmsharks4** [mtth/hdfs#146]
When using this library on Windows, it gives out this error every 2nd or 3rd connection:

<urllib3.connection.HTTPConnection object at 0x00000226EE92B748>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

You can reproduce this using:
```
client_hdfs = InsecureClient(connection_url, CommonConstants.HDFS_USER, timeout=None)
with client_hdfs.write(access_path, overwrite=True) as writer:
       json.dump(obj, writer)
```

Hope somebody can resolve this.

**Comment by mtth** [comment]
I'm not sure I can help much with this; it sounds like an unrelated connectivity issue. (Your snippet works fine with a healthy cluster.)

**Comment by Rmsharks4** [comment]
I actually did more digging and found out that this library is built on top of urllib3, and its get_connection() function uses a get_socket() utility with a fixed timeout. So changing my timeout on the outside here doesn't affect anything. Closing the issue here.
