### ISSUE TITLE
MemoryError when reading snappy encoded file

### ISSUE THREAD

**Issue by Molotch** [mtth/hdfs#147]
I'm getting a pretty non descript MemoryError when I try to read a snappy compressed file from hdfs. The file is created with the AvroReader.

If I upload the same file uncompressed there's no problems.

Any ideas what I can try to solve the problem?

>  File "main.py", line 86, in main
>     for record in reader:
>   File "Python\Python36\lib\site-packages\hdfs\ext\avro\__init__.py", line 208, in _reader
>     for record in reader:
>   File "fastavro\_read.pyx", line 672, in _iter_avro_records
>   File "fastavro\_read.pyx", line 616, in fastavro._read.snappy_read_block
>   File "fastavro\_read.pyx", line 618, in fastavro._read.snappy_read_block
>   File "Python\Python36\lib\site-packages\hdfs\ext\avro\__init__.py", line 131, in read
>     chunk = self._reader.read(nbytes)
>   File "Python\Python36\lib\site-packages\urllib3\response.py", line 507, in read
>     data = self._fp.read(amt) if not fp_closed else b""
>   File "Python\Python36\lib\http\client.py", line 448, in read
>     b = bytearray(amt)
> MemoryError

```
with AvroReader(client, file_path) as reader:
        print(reader.content)
        print(reader.schema)
        for record in reader:
            print(record)
´´´

**Comment by mtth** [comment]
Are you able to able to decode the Snappy-compressed file locally using `fastavro`?
