### ISSUE TITLE
sslerror exception

### ISSUE THREAD

**Issue by yan1990y** [mtth/hdfs#148]
I use hdfs in my private network,It can not reach Internet.
But it is https url,so when I use python to access hdfs,It will show sslerror,How can I ignore this exception?

**Comment by mtth** [comment]
You probably need to configure your client's [session](https://kite.com/python/docs/requests.Session). The `SecureClient` in [this example](https://hdfscli.readthedocs.io/en/latest/advanced.html#custom-client-support) might be helpful.
