### ISSUE TITLE
Question on using Kerberos client in hdfscli

### ISSUE THREAD

**Issue by edgarwhipple** [mtth/hdfs#15]
The documentation is not very specific on how to use or configure hdfs to use Kerberos authentication.
Please advise.

$ klist
Ticket cache: FILE:/homes/udb_grid/cache/krb_ticket
Default principal: udb_grid@YGRID.YAHOO.COM

Valid starting     Expires            Service principal
04/21/15 17:36:10  04/22/15 17:36:10  krbtgt/YGRID.YAHOO.COM@YGRID.YAHOO.COM
	renew until 04/26/15 16:30:46
04/21/15 20:43:08  04/22/15 17:36:10  HTTP/bassniumred-nn1.red.ygrid.yahoo.com@YGRID.YAHOO.COM
	renew until 04/26/15 16:30:46
$ python --version
Python 2.6.6
$ pip list | grep hdfs
hdfs (0.5.2)
$ cat /homes/udb_grid/.hdfsrc
[hdfs]
default.alias=udb_grid@bassniumred
[udb_grid@bassniumred_alias]
root=/projects/udb
url=http://bassniumred-nn1.red.ygrid.yahoo.com:50070
$ rm -f /tmp/hdfs.log; hdfscli  --list; echo; echo; cat /tmp/hdfs.log
Authentication failure. Check your credentials.

2015-04-21 21:59:49,266 | DEBU | hdfs.client > <Client(url=http://bassniumred-nn1.red.ygrid.yahoo.com:50070, root=/projects/udb)> :: Resolved path '' to '/projects/udb'.
2015-04-21 21:59:49,267 | INFO | hdfs.client > <Client(url=http://bassniumred-nn1.red.ygrid.yahoo.com:50070, root=/projects/udb)> :: Fetching status for /projects/udb.
2015-04-21 21:59:49,267 | DEBU | hdfs.client > <Client(url=http://bassniumred-nn1.red.ygrid.yahoo.com:50070, root=/projects/udb)> :: Resolved path '/projects/udb' to '/projects/udb'.
2015-04-21 21:59:49,284 | WARN | hdfs.client > <Client(url=http://bassniumred-nn1.red.ygrid.yahoo.com:50070, root=/projects/udb)> :: [401] /webhdfs/v1/projects/udb?op=GETFILESTATUS:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 401 Authentication required</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /webhdfs/v1/projects/udb. Reason:
<pre>    Authentication required</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>
</body>
</html>

2015-04-21 21:59:49,285 | ERRO | hdfs.util > Authentication failure. Check your credentials.
$

**Comment by mtth** [comment]
Add `client = KerberosClient` inside your alias' definition in `~/.hdfsrc`. It should look something like this:

```
[hdfs]
default.alias = udb_grid@bassniumred

[udb_grid@bassniumred_alias]
client = KerberosClient
root = /projects/udb
url = http://bassniumred-nn1.red.ygrid.yahoo.com:50070
```
There is also a `mutual_auth` option you can set there if you start seeing log messages because the cluster doesn't support mutual authentication (e.g. `mutual_auth = DISABLED`). Good point about the documentation, I'll add a section on configuration when I get a chance.

Let me know if any of this doesn't work.

**Comment by edgarwhipple** [comment]
2015-04-22 00:19:24,879 | ERRO | hdfs.util > Unknown client class: 'KerberosClient'
This symptom indicates that I needed to install the 'requests-kerberos' package, which I did.

I now have happiness as follows.

$ pip list | grep -E 'requests-kerberos|hdfs'
hdfs (0.5.2)
requests-kerberos (0.6.1)
$ cat ~/.hdfsrc
[hdfs]
default.alias=udb_grid@bassniumred
[udb_grid@bassniumred_alias]
client=KerberosClient
root=/projects/udb
url=http://bassniumred-nn1.red.ygrid.yahoo.com:50070
$ hdfscli --list --depth 1 /projects/udb
     -     7.1M    D    /projects/udb
     -     7.1M    D    /projects/udb/accounts
     -     7.1M    D    /projects/udb/oozie
$
Thank you for your alacritous response, and for this hdfs package.
