### ISSUE TITLE
client.status with strict=False is returning None where strict=True is returning a result

### ISSUE THREAD

**Issue by logicpeters** [mtth/hdfs#153]
Is there any reason why a client.status(some_path, strict=False) would return None, when a client.status(some_path, strict=True) returns a valid FileStatus object?  

The path does exist, and it also returns with a 200 response when I use WebHDFS ?op=GETFILESTATUS directly from a curl command.

This just started happening for me today, although it has worked correctly with the same code / version (2.1.0) for over two years running.

**Comment by mtth** [comment]
@logicpeters - apologies for the delayed reply. Is this still happening?
