### ISSUE TITLE
Format of  .hdfsrc  file not documented

### ISSUE THREAD

**Issue by maxMidius** [mtth/hdfs#16]
Hello - I am trying to use the hdfsClient  from the CLI
I  see that in the help  [ -a ALIAS]  suggests that it is optional - but it seems to require this.
So I am not seeing a sample  $HOME/.hdfsrc  file  
Can you please point to an example file 

Thanks a lot

**Comment by mtth** [comment]
Hey, good point. The README now has a [configuration section](https://github.com/mtth/hdfs#configuration) with explanations and an example (copied below for convenience). Let me know if anything remains unclear.

```cfg
[hdfs]
default.alias = foo # Used when no alias is specified at the command line.

[foo_alias]
client = KerberosClient
root = /some/directory
url = http://url.to.namenode:port

[bar_alias]
url = http://url.to.another.namenode:port
```
