### ISSUE TITLE
Using hdfs with pytest evinces deprecated usage

### ISSUE THREAD

**Issue by rlichtenwalter** [mtth/hdfs#165]
.build/miniconda/envs/build/lib/python3.8/site-packages/hdfs/config.py:15
      /<path>/.build/miniconda/envs/build/lib/python3.8/site-packages/hdfs/config.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
        from imp import load_source

    -- Docs: https://docs.pytest.org/en/stable/warnings.html

**Comment by wojdatto** [comment]
Hi, I still see the same `DeprecationWarning` emitted from the same line `from imp import load_source`:

```
venv/lib/python3.8/site-packages/hdfs/config.py:15
  /home/<snip>/venv/lib/python3.8/site-packages/hdfs/config.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import load_source
```

This issue was closed without any comments. Is there any plan to fix it (possibly by switching to `importlib`)?
