### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by dreyco676** [mtth/hdfs#17]
I seem to hit some syntax errors when running write_df with python 3.4. I wasn't sure if this is supported or not.

Could you make this clearer on your documentation of whether this is supported or not. If not is there any plans to make it compatible in the future.

**Comment by mtth** [comment]
Support is only for python 2.6 and 2.7 currently. It's displayed on [PyPI](https://pypi.python.org/pypi/hdfs/) and in `setup.py` but you're right it'd probably be good to have it more prominent.

I see you've started some compatibility work. I'm happy to review it and hopefully merge it in if you want to create a pull request later.

**Comment by dreyco676** [comment]
That'd be great. I'll let you know when its ready for you to check out.

John

**Comment by dreyco676** [comment]
Looks like the only potential hangup is Requests-Kerberos. I'll need to work on getting that ported to version 3 as well. Hopefully this doesn't spiral out of control.

**Comment by mtth** [comment]
Sounds good. You don't have to do everything at once since Kerberos support is an extension. We could indicate that it's only available for python 2.

**Comment by dreyco676** [comment]
Alright I think I got it all working. I'm not a developer by trade so I'm familiar with unit tests but have never actually used them in Python. Would you mind enlightening a heathen with how I can run them?

**Comment by mtth** [comment]
Great! You can run `hdfs`'s tests using [nose](https://nose.readthedocs.org/en/latest/) (I haven't used it with python 3, but it seems [this stackoverflow question](http://stackoverflow.com/q/22779289/1062617) has some useful information to do so). Once all tests pass, please go through the following steps:

+ Remove your IntelliJ files.
+ Clean up your commits (e.g. by squashing all of them).
+ Restore original indentation convention.

Then you can go ahead and create the pull request.

**Comment by mtth** [comment]
Hey @dreyco676 - what's your status on this? I might take a stab at it if you've stopped working on this.

**Comment by dreyco676** [comment]
It's more or less complete I just have been swamped at work with a new hire and haven't gotten around to the clean up of it. If you want to take a whack at its mostly doing try: import somepython2lib except importError: somepython3lib. That and the avro class needs print() instead of print

**Comment by wesm** [comment]
I'm also looking to get Python 3 support in github.com/cloudera/ibis going, so if you need help on this let me know

**Comment by mtth** [comment]
@wesm - Thanks. Migration is fine (the [`python3`](https://github.com/mtth/hdfs/tree/python3) branch is now compatible with both python 2 and 3), only unclear point is Kerberos support. It's possible to install the requirements for the extension manually, but I wonder if there is a better option (that doesn't require forking or integrating these).

**Comment by mtth** [comment]
Complete with the release of `2.0.0`.

**Comment by wesm** [comment]
yay, thank you! I will port Ibis whenever I can
