### ISSUE TITLE
client.checksum() to include composite_crc optional parameter

### ISSUE THREAD

**Issue by panosprotopapas** [mtth/hdfs#173]
Hello,

I've come across the need to search for the checksum of files using `hadoop fs -Ddfs.checksum.combine.mode=COMPOSITE_CRC -checksum hdfs:///path/to.file` that makes it easy to check the integrity of a file against a local copy.

Was wondering how easy this would be to be implement via the `client.checksum(filepath)` of the library.

Thanks :)

**Comment by mtth** [comment]
Hi @panosprotopapas. It doesn't look like [the underlying WebHDFS operation](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#Get_File_Checksum) supports a mode argument so I'm not sure we can efficiently implement it from this library.

**Comment by panosprotopapas** [comment]
Hi @mtth, thanks for you answer. I'm closing this since it's not an issue with the library as long as WebHDFS doesn't support it.
