### ISSUE TITLE
Tag for the 2.6.0 release?

### ISSUE THREAD

**Issue by samuela** [mtth/hdfs#176]
There are git tags on GitHub for every version except for 2.6.0. Could we get a tag for that release as well? It's helpful for packaging on eg NixOS. 

Also, looking through the commit history, I wasn't able to find a commit that bumps the version to 2.6.0, so on latest master `hdfs.__version__ == '2.5.8'` ([code](https://github.com/mtth/hdfs/blob/5b95321c316f4708cbb610c0e2d0587e54577c1f/hdfs/__init__.py#L12)).

**Comment by mtth** [comment]
Done ([tag](https://github.com/mtth/hdfs/releases/tag/2.6.0)), apologies for the delay.

**Comment by samuela** [comment]
Sweet, thanks @mtth !
