### ISSUE TITLE
Links lead to nothing in set_acl section

### ISSUE THREAD

**Issue by Andromelus** [mtth/hdfs#187]
Hello.

The three links given [here](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.set_acl) lead to nothing.

These links are:

https://hdfscli.readthedocs.io/en/latest/api.html#id4
https://hdfscli.readthedocs.io/en/latest/api.html#id7
https://hdfscli.readthedocs.io/en/latest/api.html#id9

**Comment by mtth** [comment]
Thanks - fixed.
