### ISSUE TITLE
Rebuild documentation in ReadTheDocs

### ISSUE THREAD

**Issue by dolfinus** [mtth/hdfs#194]
Hi.

There are some methods, like `Client.allow_snapshot` or `Client.create_snapshot` which have proper docstrings, but missing in [API reference](https://hdfscli.readthedocs.io/en/latest/api.html#module-hdfs.client).

According to https://readthedocs.org/projects/hdfscli/builds/, the latest build was more than 3 years ago:
![image](https://user-images.githubusercontent.com/4661021/233015195-1d6e0a85-cc68-49de-b619-2f35cbcd412d.png)

And these methods were added 2 years ago in #167.

@mtth Could you please rebuild `latest` documentation and enable integration with ReadTheDocs for this repo?

**Comment by mtth** [comment]
@dolfinus - thanks for pointing it out. The docs have been rebuilt.

**Comment by dolfinus** [comment]
Thanks!
