### ISSUE TITLE
Mixed path separators when using Windows

### ISSUE THREAD

**Issue by dreyco676** [mtth/hdfs#20]
os.path.join() will use whatever separator the local system uses. We should force to "/" and not allow mixed separators, lest you get a 400 bad request from WebHDFS.

In the function 'resolve' in 'client.py'

path = osp.normpath(osp.join(self.root, path))

should be changed to 

path = osp.normpath(osp.join(self.root, path)).replace("\\\\","/")

EDITED because formatting ate a '\' 

There are several other places this should be enforced. Perhaps there is a better way to globally force it?

**Comment by mtth** [comment]
Should be fixed in 658115057737e40e47edb77d0597081a880f992b (version `>=1.0.1`). I don't have a Windows machine on hand so let me know if not!

**Comment by dreyco676** [comment]
Order of operations is off.

return quote(path, safe='/=').replace(os.sep, '/')

Should be this, otherwise it encodes '\' as '%5C' and does not do replacement.

return quote(path.replace(os.sep, '/'), safe='/=')

**Comment by mtth** [comment]
You're very much correct. Fixed in cb894738613629e6fc8ec0fd13cff50d685236b3 (`1.0.2`).
