### ISSUE TITLE
Don't use 'hdfs' as the binary name

### ISSUE THREAD

**Issue by QwertyManiac** [mtth/hdfs#27]
Apache Hadoop scripts on PATH use "hdfs". This module's default installation overwrites that and breaks scripts that rely on the Apache Hadoop one, when installed on a host that already has Apache Hadoop installed on it.

Could the binary name be changed?

**Comment by QwertyManiac** [comment]
(I understand one can change it, but the default is in conflict and causes trouble at places who don't follow the clear guide :))

**Comment by mtth** [comment]
I'll think about it. While I'm not fond of having the CLI named differently from the package, the conflict might make the change worth it. It should be fine to integrate this in the next major release.

**Comment by mtth** [comment]
Fixed in `2.0.0`.
