### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by wesm** [mtth/hdfs#28]
I'm using `Client.status` internally in ibis to determine whether a file exists, and this results in various scary logger warnings being printed in normal user actions. Would it be possible to make this configurable so I can hide these messages somehow?

**Comment by mtth** [comment]
The warning messages on non-`2XX` responses (e.g. `404`s for missing files) will be removed in `2.0`. Is this sufficient for your use-case?

About your particular example, if you use Kerberos authentication, you'll still get an error-level log message from mutual authentication not being available on `404`s (if you enable it). Is this (or suppressing logs from `requests_kerberos`) acceptable?

**Comment by wesm** [comment]
This works for me. Let's leave this open and I'll confirm that all is sorted after 2.0 is out?

**Comment by mtth** [comment]
Sounds good.

**Comment by mtth** [comment]
Closing this since `2.0` was integrated into `ibis`.

@wesm - feel free to reopen if this is still an issue.

**Comment by wesm** [comment]
is there a way to direct the `hdfs` logging statements into some other logging sink?

**Comment by mtth** [comment]
As in change the loggers' names? Is this for the same use-case (there shouldn't be any scary messages from the `hdfs` logger when using `strict=False`)?
