### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by wesm** [mtth/hdfs#30]
It will make it easier for others to contribute to this package if it adheres to Python style best practices (e.g. 4 spaces per indent)

**Comment by mtth** [comment]
You're right.

Some of PEP8's recommendations make the code less readable and "elegant" IMHO though (e.g. the [indentation guidelines](https://www.python.org/dev/peps/pep-0008/#indentation)). I'll think about it.

**Comment by wesm** [comment]
I don't agree with all those, but the "aligned with first delimiter" style is what I prefer. Using 4 spaces for indentation is the biggest off-putting thing about the codebase for me personally.

**Comment by mtth** [comment]
I'll consider :).
