### ISSUE TITLE
AvroReader - 'module' object is not callable

### ISSUE THREAD

**Issue by zoltan-fedor** [mtth/hdfs#32]
When using confluent schema registry (https://github.com/verisign/python-confluent-schemaregistry) together with this module for AvroReader, then it fails with 'module' object is not callable.

'module' object is not callable
```File "/venv1/lib64/python3.4/site-packages/hdfs/ext/avro/__init__.py", line 195, in __enter__\n    self._schema = next(self._records) # Prime generator to get schema.\n',
File "/venv1/lib64/python3.4/site-packages/hdfs/ext/avro/__init__.py", line 186, in _reader\n    avro_reader = fastavro.reader(_SeekableReader(bytes_reader))\```   

Pseudo-code:   
```
from hdfs import InsecureClient
from hdfs.ext.avro import AvroReader, AvroWriter
from confluent.schemaregistry.client import CachedSchemaRegistryClient
from confluent.schemaregistry.serializers import MessageSerializer

schema_registry_client = CachedSchemaRegistryClient(url='http://'+settings['schema_registry_server'])
serializer = MessageSerializer(schema_registry_client)
with AvroReader(hdfs_client, settings['hdfs_target_file']) as reader:
    pass
```

**Comment by zoltan-fedor** [comment]
Actually this might be better fixed in the hdfs pacakage itself in the hdfs.ext.avro module's _init_.py line be replacing:

avro_reader = fastavro.reader(_SeekableReader(byted_reader))
with
avro_reader = fastavro.reader.iter_avro(_SeekableReader(byted_reader))

**Comment by mtth** [comment]
These imports are a bit tricky because we should also make sure that we get the Cython optimized code when possible. Could you check which version of `fastavro` you have?

**Comment by zoltan-fedor** [comment]
I have the latest, fastavro 0.9.6

**Comment by mtth** [comment]
`fastavro` is pinned to `0.9.2` in `hdfs`'s dependencies to avoid further breaking changes (since https://github.com/mtth/hdfs/commit/7ea9d30430278e9ab6f763c99b16eaa1f5fb8709). I wonder if this is one of them. Could you try running your code after downgrading to `0.9.2`?

**Comment by zoltan-fedor** [comment]
Downgraded to fastavro 0.9.2 and my fix was still working. Without the fix it was still failing the same way as above, so it seems this fix is needed for 0.9.2 too.

**Comment by mtth** [comment]
Thanks for checking. Will take a closer look tonight.

**Comment by zoltan-fedor** [comment]
Gr8, thanks!

**Comment by mtth** [comment]
Should be fixed in https://github.com/mtth/hdfs/commit/0d78017f1a2bcd9e8b3b9eab00bc7212365bfe69 (`>=2.0.4`) - thanks for reporting the issue!

**Comment by zoltan-fedor** [comment]
Thanks for the quick fix!
