### ISSUE TITLE
optional user parameter for InsecureClient

### ISSUE THREAD

**Issue by jischebeck** [mtth/hdfs#33]
When using hdfs from Windows, the Username often differs from the username on hadoop. 

Can you add an example for passing the username to the Insecure Client to the Quickstart tutorial?

**Comment by mtth** [comment]
To clarify: you're aware that `InsecureClient` takes a `user` argument, and would like the quickstart documentation to have an example using it?

**Comment by jischebeck** [comment]
Hi Matthieu,
yes, that's right. It took me a while to find it out -- looking only on
parameters on the Client class.
Maybe that eases the life for other users.
Jan

E.g.

client = InsecureClient('http://host:port','username')


2015-12-05 17:56 GMT+01:00 Matthieu Monsch <notifications@github.com>:

**Comment by mtth** [comment]
That makes sense. Just added the parameter to a couple examples in 548b3d47013a81fbb1385dd7c4a93cca1eaf40d5.
