### ISSUE TITLE
InvalidSchema: No connection adapters were found

### ISSUE THREAD

**Issue by eahlberg** [mtth/hdfs#37]
Hi,

I've setup WebHDFS and I'm trying to use the CLI with:

    $ hdfscli --alias=dev
    In [1]: CLIENT.list('/')

However, I'm getting the following error:

    InvalidSchema: No connection adapters were found for 'hdfs://<HOST>:<PORT>/webhdfs/v1/<FOLDER>'

The WebHDFS REST API works fine with e.g.:

    curl "http://<HOST>:<PORT>/webhdfs/v1/<FOLDER>?op=LISTSTATUS"

My config (~/.hdfscli.cfg) looks like:

    [global]
    default.alias = dev

    [dev.alias]
    url = hdfs://<HOST>:<PORT>

Am I using hdfs incorrectly or is there something sketchy going on? And it should work without setting up HttpFS, right?

**Comment by mtth** [comment]
The `url` parameter in your config should be `http://` (instead of `hdfs://`).

**Comment by eahlberg** [comment]
Ok thanks, my bad!
