### ISSUE TITLE
How is walk supposed to be used?

### ISSUE THREAD

**Issue by OskarPersson** [mtth/hdfs#45]
How is `walk` supposed to be used?

I'm trying `(path, dirs, files) = CLIENT.walk("/", depth=1)` but this gives me an error:

```
>>> (path, dirs, files) = CLIENT.walk("/", depth=1)
Traceback (most recent call last):
    File "<console>", line 1, in <module>
ValueError: need more than 1 value to unpack
```

**Comment by mtth** [comment]
It works similar to [`os.walk`](https://docs.python.org/2/library/os.html#os.walk). The function returns a generator of tuples:

```python
for path, dirs, files in CLIENT.walk('/', depth=2): # 1 will only give you the input directory
  print path # For example.
```
