### ISSUE TITLE
Obtain the plain file stream (instead of a contextmanager generator) while reading

### ISSUE THREAD

**Issue by cherrot** [mtth/hdfs#47]
Suppose such a circumstance: I have implemented a middleware to serve a file object from HDFS to the downstream application. So in the middleware I wrote:

```python
# file_storage.py
def open(path):
    return hdfs_client.read(path)
```

And in my downstream app I wrote somethin like:
```python
# app.py
with contextlib.closing(file_storage.py.open(path)) as stream:
    stream.read()
```

If I wrapped `hdfs_client.read` into a with context, then the downstream app would read a closed resource.

So is there someway to obtain the plain file stream directly? Or shall we replace the `contextmanager` decorator by a more generic approach?

**Comment by mtth** [comment]
Why not have your middleware expose a context manager interface? The expected usage would be more explicit too. Something like:

```python
from contextlib import contextmanager

@contextmanager
def open(path):
  with hdfs_client.read(path) as reader:
    yield reader

# Sample usage:
with open('foo') as reader:
  pass # Do something with the reader.
```

**Comment by cherrot** [comment]
How about wrapping the reader object (`codecs.reader`, `res.raw`, etc) in a class, which has `__enter__` and `__exit__` method to implement a context manager? Just like what is described in the following link:

http://stackoverflow.com/questions/35350897/python-standard-function-and-context-manager

**Comment by mtth** [comment]
The `contextmanager` decorator is sugar for implementing your own class with `__enter__` and `__exit__` methods. You can already do what you want by calling these methods yourself.

For example:

```python
class Wrapper(object):

  """A basic wrapper around the context manager returned by `read`.

  It can be used both inside a `with` block or directly from a function call.
  This is a very basic example, you probably will want to proxy more methods
  than just `read` and add error handling.

  """

  def __init__(self, cm):
    self.cm = cm
    self.reader = cm.__enter__()

  def __enter__(self):
    return self.reader

  def __exit__(self, *args):
    self.cm.__exit__(*args)

  def read(self):
    return self.reader.read()

# Sample usage:

def hdfs_open(path):
  return Wrapper(hdfs_client.read(path))

# Direct usage.
reader = hdfs_open('foo')
print reader.read()

# Inside a `with` block.
with hdfs_open('foo') as reader:
  print reader.read()
```

At this point I'm not convinced this is worth adding to the library itself for a couple reasons:

+ It encourages unsafe behavior (which might keep connections open).
+ It requires manually proxy-ing all reader methods.

**Comment by cherrot** [comment]
Thanks for your suggestion! It is an acceptable and workable solution for me.

_Personally I think it is user's responsibility to maintain the underlying resource (files, sockets, etc), not the developer's ;-)_
