### ISSUE TITLE
Install HDFSCLI with kerberos extension over setup.py

### ISSUE THREAD

**Issue by sansagara** [mtth/hdfs#50]
Hi mtth.
In our company, we use our own tarballs as the source for installing modules on the servers. We use `setup.py install` The issue i have installing HDFSCLI this way, is that i require the Kerberos extension, wich is not installed by default. 

I've googled around, and that seems to be a missing feature on setup.py. So wanted to ask if you can think of a workaround for the Kerberos extension to be installed as the default. (i thought moving the kerberos.py file out one step would do the trick, but the tarball gets messed).

Any ideas?

**Comment by mtth** [comment]
Hey @sansagara. Not sure I follow - do you mean that since Kerberos is an optional dependency, there is no way to install it using the tarball approach? Would it work to install the Kerberos requirements separately (e.g. in their own tarball)? Could you use `pip` instead of `setup.py` to install from the tarballs?

**Comment by sansagara** [comment]
I thought about installing the kerberos dependency apart, but i think it will fail to load the kerberos.py file inside the ext folder, right?. It happened on me when starting hdfs on the cli. I think i may come up with some way of using pip for this, but would really prefer to use the way it is deployed right now.

To explain a little bit more: The issue at hand is that for our environment, we handle package installs with a shell script that unzips the tarballs and installs them with the `python3 setup.py install`. That way of doing it don't allow external modules to be installed.(not flag, nothing). But i guess that is more a flag in setup.py than it is in hdfscli.

**Comment by mtth** [comment]
I believe `ext/kerberos.py` is always included. You won't be able to import it without its dependencies but if you also include their tarballs, I assume it'll work. Can you check by running the script locally?

**Comment by sansagara** [comment]
So, you are suggesting that manually installing the `'kerberos': ['requests-kerberos>=0.7.0']` dependency would make the trick.... Let me try and check!.

**Comment by sansagara** [comment]
Ok, i was able to make everything work as intended just by manually installing request-kerberos.
Ty mtth.

**Comment by mtth** [comment]
Great! Happy to hear.
