### ISSUE TITLE
Question about stating root directory.

### ISSUE THREAD

**Issue by sansagara** [mtth/hdfs#51]
Hi htth.
Just a quick question on something i realized when using hdfscli on a script to stat my prod hdfs.
When using stat on root in order to get the bytes, like `client.content('/')['length']` i get a value, say X.
Shortly after that, i walk on a subdirectory, stating each one of them and  also storing  the lenght, like:

```
fpaths = [
    psp.join(dpath, ddir)
    for dpath, ddirs, fnames in client.walk('/', 3)
    for ddir in ddirs
    ]

for item in fpaths:
     details = client.content(item)
     totalBytes = details['length']
```
For some directories on this walk (Y), i get some lengths that are up to 300% more than what i get for root (X). Is this expected? What should i use in order to compare the length of a particular subfolder in relation to the complete hdfs length?

TY

Edit:
Nevermind, i just found out that this particular issue is with my hdfs. Apparently, it stops iterating over root when getting to a particular folder. So the same happens when doing:
`hdfs dfs -du -h /`  -> gets only first folder size
and:
`hdfs dfs -du -h -s /` ->gets the complete list of first-folder directories.

Workaround is to do the walk by myself. Thank you.

**Comment by mtth** [comment]
Looks like you found a solution :).

I don't remember how directories' `length` is computed (e.g. whether it includes files in subdirectories or not). I thought it was the total size but if you observe that the numbers don't add up for your setup walking is safer.
