### ISSUE TITLE
Support for Get_ACL_Status

### ISSUE THREAD

**Issue by sansagara** [mtth/hdfs#52]
Hi @mtth .
It would be nice if WebHDFS method [Get_ACL_Status](https://hadoop.apache.org/docs/stable2/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#Get_ACL_Status) would be supported. I need a quick way to get the ACL details of a specific path/file in HDFS.

If you like the idea, i would like to contribute and add the feature. Any suggestions on where to look at  first?

**Comment by mtth** [comment]
That sounds like a good idea, thanks for offering to contribute!

The various methods in the `Client` class should provide a good starting point (for example [`client.checksum`](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L874)). You'll want to add a [raw API method](https://github.com/mtth/hdfs/blob/master/hdfs/client.py#L185) for the ACL endpoint (there is some magic under the hood there but it'll be very similar to the other ones) and call it from the new public method. Let me know if I can be of any help.

**Comment by sansagara** [comment]
My first attempt is on [PR #53](https://github.com/mtth/hdfs/pull/53)

**Comment by sansagara** [comment]
I've tested this and can confirm it is returning the expected JSON object.
Some test outputs are:

```
In [10]: CLIENT.acl_status('/user/hive/warehouse')
Out[10]:
{'entries': ['user:hive:rwx',
  'user:svchadoopjobs:rwx',
  'group::rwx',
  'default:user::rwx',
  'default:user:hive:rwx',
  'default:user:svchadoopjobs:rwx',
  'default:group::rwx',
  'default:mask::rwx',
  'default:other::--x'],
 'group': 'hive',
 'owner': 'hive',
 'stickyBit': True}

In [11]: CLIENT.acl_status('/user')
Out[11]: {'entries': [], 'group': 'supergroup', 'owner': 'hadoop', 'stickyBit': False}
```

I can't come up with good ideas on tests besides cheking the existence of the 'entries' key/node in the result.

**Comment by mtth** [comment]
Great! I commented on the PR about the CI failures; once this is resolved, we should be ready to merge.

**Comment by mtth** [comment]
Merged; thank you for contributing!
