### ISSUE TITLE
upload files from local to hdfs failed

### ISSUE THREAD

**Issue by tenyue** [mtth/hdfs#55]
`>>> from hdfs import Client
>>> client = Client('http://172.17.201.16:50070')
>>> client.list('/')
[u'abc', u'demo', u'input', u'tmp', u'user']
>>> client.upload('/user/hdfs/','/home/spider/haha.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hdfs/client.py", line 547, in upload
    raise err
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7fb776c84950>: Failed to establish a new connection: [Errno -2] Name or service not known`
But , i upload file in this way on the server cluster is successful

**Comment by abigbigbird** [comment]
can this have any other solutions?

**Comment by tenyue** [comment]
hello,
first, you should be set user to hdfs about dr.who
second, you should be reduce directory permissions

**Comment by abigbigbird** [comment]
thanks a lot, I had configure hosts file which resolve it!

**Comment by lavenkin** [comment]
I get the error
```
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10e06ed68>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
```

**Comment by NoraGithub** [comment]
What if the Hadoop doesn't expose the slaver? In my option, Hadoop should only be known as the namenode. Any idea?
