### ISSUE TITLE
upload files from local to hdfs failed

### ISSUE THREAD

**Issue by tenyue** [mtth/hdfs#56]
-----------------------------
>>> from hdfs import *
>>> client = Client('http://172.17.201.16:50070',proxy='hdfs')
>>> client.upload('/user/hdfs/','/home/xxxxx/haha.txt')
-----------------------------
ERROR:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hdfs/client.py", line 484, in upload
    raise err
hdfs.util.HdfsError: Failed to obtain user group information: org.apache.hadoop.security.authorize.AuthorizationException: User: dr.who is not allowed to impersonate hdfs

**Comment by mtth** [comment]
This looks like a configuration issue. Make sure that you specify the correct user, for example by using an [`InsecureClient`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.InsecureClient), and that this user is allowed to impersonate your proxy. In most simple cases, you don't even need to use a proxy:

```python
from hdfs import InsecureClient

client = InsecureClient('http://172.17.201.16:50070', user='tenyue')
# ...
```

 [This stackoverflow question](http://stackoverflow.com/q/36909002/1062617) might also be helpful.
