### ISSUE TITLE
Implement HDFS trash functionality in hdfs module

### ISSUE THREAD

**Issue by schaffino** [mtth/hdfs#57]
After an accidental deletion of some reasonably important data and thinking I'd be able to get some files back from Trash i've discovered that webhdfs does not enable hdfs Trash behind the scenes and it's considered the clients responsibility to do this.

Is this something that could be incorporated into the hdfs module? I've had a look around and it looks like hue has implemented some of this functionality in its internal code.

https://github.com/cloudera/hue/blob/master/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py

**Comment by mtth** [comment]
This sounds like a good idea. Is it something you'd be interested in contributing?

**Comment by gdgt** [comment]
PR #90

**Comment by mtth** [comment]
Thanks again for the PR @gdgt! From version `2.5.0` onwards [`client.delete`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.delete) has a `skip_trash` option which allows for safer deletes when `False`:

```python
client.delete('my/path', skip_trash=False) # Will move the path to a trash folder.
```

Note that:

+ The cluster must be configured to support it (in particular it requires Hadoop 2.9).
+ The default is `skip_trash=True` for backwards compatibility.
