### ISSUE TITLE
Support for Set ACL

### ISSUE THREAD

**Issue by sansagara** [mtth/hdfs#59]
Hi @mtth. I'm actually adding support for [Set ACL](http://hadoop.apache.org/docs/r3.0.0-alpha1/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#Set_ACL). I'm doing a PR as soon as i test this on my cluster!.

**Comment by mtth** [comment]
Merged https://github.com/mtth/hdfs/pull/60 and released as `2.0.12`; thank you @sansagara!
