### ISSUE TITLE
Question about Custom Client

### ISSUE THREAD

**Issue by sansagara** [mtth/hdfs#62]
Hi @mtth . I happen to be using hdfscli with the default ~/.hdfscli.cfg approach. However, after a recent server change, i had to re-create the file. So i was thinking to avoid the file (and even the use of a Environment Variable) by directly passing the parameters to the Client programmatically.

I'm actually just using `client = Config().get_client()` on the code. And for the config file:

> [global]
> default.alias = prod
> autoload.modules = hdfs.ext.kerberos
> 
> [prod.alias]
> url = http://cluster.domain:14000/
> client = KerberosClient

Any idea how to avoid using the config file with this setup? I've taken a look at:
http://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client
But cant seem to quite get how i'm supposed to use Kerberos client with this...

**Comment by mtth** [comment]
The simplest is probably to instantiate the [`KerberosClient`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.ext.kerberos.KerberosClient) directly:

```python
from hdfs.ext.kerberos import KerberosClient

client = KerberosClient(url='http://cluster.domain:14000')
```

All the options in the configuration get passed as keyword arguments to their respective client constructor when you call `config.get_client`, so the two should be equivalent given your configuration. (Only the `timeout` option is [lightly pre-processed](https://github.com/mtth/hdfs/blob/master/hdfs/config.py#L113) currently for convenience.)

**Comment by sansagara** [comment]
Thank you!. It is so obvious now... 
Maybe you should consider putting this somewhere on the docs?
greetings!
