### ISSUE TITLE
KerberosClient Question

### ISSUE THREAD

**Issue by ericjang96** [mtth/hdfs#63]
Hi, I have a question about how the KerberosClient works at: http://stackoverflow.com/questions/41292891/how-does-the-hdfscli-library-decide-which-kerberos-principal-to-use

Basically, it seems like the KerberosClient doesn't have any parameters to specify the keytab location or principal to login with. How does it find the keytab and decide which principal to use? Thank you.

**Comment by mtth** [comment]
Hey, HdfsCLI delegates all Kerberos-related logic to the underlying [`requests-kerberos`](https://github.com/requests/requests-kerberos) library. On some OS's it seems possible to [specify an explicit principal](https://github.com/requests/requests-kerberos#explicit-principal), would that be sufficient for your use-case? If so, I can submit a patch to let you pass in the argument to the `KerberosClient`.

**Comment by ericjang96** [comment]
Would it be possible to explicitly pass in the keytab file location as well? If not, a patch for explicitly specifying a principal in the KerberosClient will be sufficient. Thank you!

**Comment by mtth** [comment]
It doesn't look like `requests-kerberos` supports passing in the keytab file's location. You might want to check there (and perhaps bring it to their attention if that's the case). In any case, I'll push a patch that forwards any `KerberosClient`  keyword arguments through so you'll be able to access any functionality they provide.

**Comment by mtth** [comment]
[`2.0.14`](https://pypi.python.org/pypi/hdfs/2.0.14) is out with the change!

**Comment by ultrabug** [comment]
Thanks for this guys. I have the same use case as @ericjang96 with a principal/keytab need for kerberos authentication.

@ericjang96 if you happen to ask the requests-kerberos guys about this first and get a proper solution for this, I'd appreciate your feedback thanks !

**Comment by hbf0803** [comment]
Does  the latest version  support  initialize KerberosClient  with parameter to specify the keytab location ?
