### ISSUE TITLE
Functionality to search for files by name

### ISSUE THREAD

**Issue by ericjang96** [mtth/hdfs#64]
It seems like there is no method for searching files by name in the current API. I want to be able to pass in a search query like "samp" and get a list of files/folders that contain the string (e.g. "samplefile.txt", "samplefolder", etc.)

The only way I can think of for searching currently is by using this method https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.walk and iterating through all of the files/folders and looking for ones with names that match the input string. Not sure how efficient this solution would be..

**Comment by mtth** [comment]
Unfortunately HDFS doesn't provide a direct mechanism for this AFAIK (neither do most filesystems). We likely can't do better than using `client.walk` (see [this question](http://stackoverflow.com/q/6297533/1062617), where the recommendation is an equivalent `hdfs dfs -ls -R / | grep [search_term]`).
