### ISSUE TITLE
Kerberos Question

### ISSUE THREAD

**Issue by ericjang96** [mtth/hdfs#66]
When HDFS is set up with Kerberos, there are different principals for each service as shown here: https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-common/SecureMode.html

When authenticating with the KerberosClient, do I need to use the NameNode principal or WebHDFS principal? (i.e. nn/_HOST@REALM.TLD or http/_HOST@REALM.TLD)

**Comment by mtth** [comment]
I'm not an expert and I don't have access to a Kerberized cluster anymore to test this but my guess is neither. These are principals used by the internal Hadoop systems while you'd likely want to authenticate as a user (e.g. yourself).
