### ISSUE TITLE
Progress tracking for write method

### ISSUE THREAD

**Issue by ericjang96** [mtth/hdfs#67]
Can you add progress tracking to the "write" method like there is for the "upload" method? I want to be able to directly write binary data to my HDFS and track track the progress. I can't use the "upload" method because there is no local_path

**Comment by mtth** [comment]
You can already do that:

+ By using the file-like interface (i.e. passing `data=None`).
+ By passing in a generator as `data` argument and performing some side-effect (e.g. updating a counter) each time it yields.

For example, using the former:

```python
with client.write('events.jsonl', encoding='utf-8') as writer:
  for line in lines: # Sample data.
    writer.write(line)
    # Perform some progress update here...
```
