### ISSUE TITLE
support hfile/avro for hbase ?

### ISSUE THREAD

**Issue by sandys** [mtth/hdfs#68]
hi,
similar to https://github.com/traviscrawford/python-hdfs/blob/master/hdfs/hfile.py , is it possible for you to support the HBase/HFile format ? And especially being able to read write AVRO data from hbase.

References:
* http://blog.cloudera.com/blog/2012/06/hbase-io-hfile-input-output/
* https://github.com/kite-sdk/kite 
* http://blog.cloudera.com/blog/2014/06/how-to-use-kite-sdk-to-easily-store-and-configure-data-in-apache-hadoop/

**Comment by mtth** [comment]
Hey, I'm not familiar with HBase but it looks different from [`HFile`](https://github.com/traviscrawford/python-hdfs/blob/master/hdfs/hfile.py). The former is a fully-fledged database built on top of HDFS, the latter is a python abstraction to make files on HDFS behave like local files.

Supporting HBase queries here would be cool but I'm not sure it belongs (this library is a wrapper around WebHDFS while we'd be better off talking to HBase for this).

HdfsCLI's file abstraction (returned from `client.read` and `client.write`) is already similar to `HFile`'s except that it is non-seekable (I doubt we'd be able to have a reasonably performant implementation of this on top of WebHDFS).
