### ISSUE TITLE
Video uploading to HDFS

### ISSUE THREAD

**Issue by dvigneshwer** [mtth/hdfs#70]
`client.write('/'+str(hfds_video_loc)+'/'+str(video_name),data=str(local_video_loc))`

Wanted to upload a video to the HDFS, the file is getting created but the contents are not getting uploaded.

Is it possible to upload a video using the Hdfscli python module? 

I am planning to convert the video to a pickle file and try again.

**Comment by dvigneshwer** [comment]
Converted the video to pickle file and it also does not upload as well using the client.write() function.

**Comment by mtth** [comment]
What's the error you get?

From looking at your snippet: [`write`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.write) accepts a `file`-like object as input, If you'd like to specify a local path to the video, use [`upload`](https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.upload) instead.

**Comment by dvigneshwer** [comment]
**What's the error you get?**
I am not getting any errors, the file is getting created but the content is not getting uploaded.
For example, I am uploading a video of 10mb to my HDFS server the file name of the video is getting created in the HDFS directory with a size of 49B but the contents of the video are not getting uploaded. I should not have used write method. 

**upload method works perfectly for this use case:)** 
`hdfs_client.upload('/'+self.hfds_video_loc+'/'+self.video_name,self.local_video_loc,overwrite=True)
`
I actually went ahead and wrote the curl command in python itself,
```
# Getting the data node information
Namenode_Response = os.popen("curl -i -X PUT '"+self.hdfs_server+"/webhdfs/v1/"+self.hfds_video_loc+"/"+self.video_name+"?user.name="+self.hdfs_user+"&op=CREATE&overwrite=true'").read()

# Getting the information of the datalocation 
data_location = Namenode_Response.split("Location")[1].split("\r")[0].split(" ")[1]

# Uploading the data
data_node_resp = os.popen("curl -i -X PUT -T "+self.local_video_loc+" '"+str(data_location)+"'").read()
logging.info("Response from the datanode"+str(data_node_resp))
```

Thanks for the support and help @mtth Really appreciate it :)
