### ISSUE TITLE
example with timeout

### ISSUE THREAD

**Issue by josephykwang** [mtth/hdfs#71]
it is not clear how timeout should be specified.  in HTTPRequest, one can specify request_timeout.

HTTPRequest(url_with_host, method=method, body=body, request_timeout=HDFS_TIMEOUT)

we are trying to upload a very large file. it is also not clear if setting parallelism will help. right now, we are getting timeout.

**Comment by mtth** [comment]
You can specify a timeout when instantiating a client ([reference](http://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client)). For example, using `InsecureClient`:

```python
from hdfs import InsecureClient
client = InsecureClient('http://hostname:port', timeout=10000)
```

If you use a configuration file, simply specify a `timeout` configuration value:

```cfg
[dev.alias]
url = http://hostname:port
timeout = 10000
```

Finally, if you're uploading a single file, the built-in parallelism won't help. To benefit from it, you could split the large file into separate chunks and upload the containing directory.
