### ISSUE TITLE
ERROR	No alias specified and no default alias found.

### ISSUE THREAD

**Issue by tribbloid** [mtth/hdfs#73]
The default alias should be under ~/..hdfscli.cfg but the file is not there.
Also, why alias is required to use HDFS?

**Comment by mtth** [comment]
The alias is useful to save you from specifying your cluster's configuration explicitly each time. You don't have to have an alias to use the python API though. For example if your cluster is configured with default settings, you can just specify a URL:

```python
from hdfs import InsecureClient
client = InsecureClient('http://host:port', user='you')
```

The [quickstart page](https://hdfscli.readthedocs.io/en/latest/quickstart.html) also has more background and information if you're curious.
