### ISSUE TITLE
Password Authentification using Kerberos

### ISSUE THREAD

**Issue by pglopezamaya** [mtth/hdfs#74]
Hello I'm trying to authenticate using kerberos. I would like to know if there is a way of passing the password on principal and not to kinit before to generate a tocken.

When I was the password while initializating the KerberosClient class:
```
 client = KerberosClient(url,principal='myuser@EXAMPLE.COM:password')
```

I get the following error if no kinit has been done and I try to pass the password with the principal:
```
(('Unspecified GSS failure.  Minor code may provide more information', 851968), ("Can't find client principal myuser@EXAMPLE.COM:password in cache collection", -1765328243))
```

If I do a kinit before and I don't pass the password while building the KerberosClient I manage to get the connection because there is a tocken in the cache with that principal.

**Comment by mtth** [comment]
Hey. The `KerberosClient` delegates all things Kerberos to the underlying [`requests-kerberos`](https://github.com/requests/requests-kerberos) library (more specifically it [forwards all non-HDFS arguments to the underlying `HTTPKerberosAuth`](https://github.com/mtth/hdfs/blob/master/hdfs/ext/kerberos.py#L68)). I'm not sure whether it supports this functionality, you might have better luck asking the maintainers of the library.
