### ISSUE TITLE
parts() function

### ISSUE THREAD

**Issue by tenkeiu8** [mtth/hdfs#75]
Hi, 

I have a file on hdfs which is appended every hour by spark program (SaveMode.Append mode) in crontab. It seems there is an issue with parts() function as it returns only parts with distinct part-r-XXXXX part like so:

File Listing with parts()
['part-r-00000-be712982-8f95-48e4-912d-c0051000edc0', 'part-r-00001-be712982-8f95-48e4-912d-c0051000edc0', 'part-r-00002-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00003-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00004-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00005-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00006-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00007-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00008-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00009-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00010-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00011-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00012-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00013-2199dfb2-b383-4751-8638-6cd424642de7']

File Listing with list()
['_SUCCESS', 'part-r-00000-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00000-4e50183b-74de-4c1c-8fda-985ec8c709f7', 'part-r-00000-55723d2a-6872-4e68-90f8-e15ca8a86c63', 'part-r-00000-5ce08d27-823d-457a-ad2d-1c88457c7185', 'part-r-00000-be712982-8f95-48e4-912d-c0051000edc0', 'part-r-00001-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00001-4e50183b-74de-4c1c-8fda-985ec8c709f7', 'part-r-00001-55723d2a-6872-4e68-90f8-e15ca8a86c63', 'part-r-00001-5ce08d27-823d-457a-ad2d-1c88457c7185', 'part-r-00001-be712982-8f95-48e4-912d-c0051000edc0', 'part-r-00002-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00003-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00004-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00005-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00006-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00007-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00008-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00009-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00010-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00011-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00012-2199dfb2-b383-4751-8638-6cd424642de7', 'part-r-00013-2199dfb2-b383-4751-8638-6cd424642de7']

I am using hdfs (2.0.16)

**Comment by mtth** [comment]
Hey, this is WAI though the documentation should be more explicit. I'll update it to mention that if there is more than one part-file per partition, `parts` will select one arbitrarily.

IIRC, it's not good practice to have different jobs output to the same parts-folder; instead of having:

+ `some_dir/`
  +  `part-01-abc`
  +  `part-01-def`
  +  `part-02-ghi`
  +  ...

It would be cleaner to have:

+ `some_dir/`
  + `timestamp1/`
    +  `part-01-abc`
    +  `part-02-ghi`
    + ...
  + `timestamp2/`
    +  `part-01-def`
    + ...
