### ISSUE TITLE
AvroWriter with codec='snappy' doesn't work

### ISSUE THREAD

**Issue by kyunam** [mtth/hdfs#78]
How do I make it work?

File "C:\Python27\ArcGIS10.5\lib\site-packages\hdfs\ext\avro\__init__.py", line 315, in _write
    block_writer = fastavro._writer.BLOCK_WRITERS[self._codec]
KeyError: 'snappy'

Thanks!
Q

**Comment by mtth** [comment]
Do you have `python-snappy` installed? Looks like the codec only gets installed if [`snappy` can be imported](https://github.com/tebeka/fastavro/blob/0adfffba422ab36b0379934d5cc237dbf3536b9c/fastavro/writer.py#L438).

**Comment by mtth** [comment]
Response timeout.
