### ISSUE TITLE
HdfsError without message

### ISSUE THREAD

**Issue by mrares** [mtth/hdfs#81]
In certain circumstances (calling .status on a connection where the NN is in STANDBY) the _on_error callback doesn't populate the message attribute with anything so you get a HdfsError(None, exception=...)

I also get the line: hdfs.util.HdfsError: Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error

**Comment by mtth** [comment]
Thanks for reporting this. It'll be hard for me to find the correct fix since I can't reproduce it; would you be able to provide more information? For example the underlying error (which fields are un/set, etc.). A PR would also be most welcome.

**Comment by mrares** [comment]
Hi, tbh I shamelessly fixed it as per https://github.com/mrares/incubator-airflow/tree/fix-HdfsError, but idk if that's PR material
