### ISSUE TITLE
how to assign kerberos principal

### ISSUE THREAD

**Issue by qiangchow** [mtth/hdfs#82]
Hi,

i want to use kerberos to access hdfs. These are my codes:

```
from hdfs.ext.kerberos import KerberosClient
directory_path = "/tmp/hdfs_test/"
hdfs_client = KerberosClient("http://192.168.200.138:50070/", mutual_auth="OPTIONAL")
print hdfs_client.content(directory_path)
```

but how to assign principal just like "USER@REALM.COM"? i tried use "proxy="USER@REALM.COM"" and it does not work, want is the usage of this parameter?
thanks

**Comment by mtth** [comment]
If your OS supports it, you can pass it as `principal` argument to your client:

```python
hdfs_client = KerberosClient(
  "http://192.168.200.138:50070/",
  mutual_auth="OPTIONAL",
  principal="USER@REALM.COM")
```

Take a look at `request-kerberos`' [documentation](https://github.com/requests/requests-kerberos#explicit-principal) for more info. https://github.com/mtth/hdfs/issues/63 might also be helpful.
