### ISSUE TITLE
Username/password connection

### ISSUE THREAD

**Issue by jrevillard** [mtth/hdfs#84]
Dear all,

I'm trying to access webHDFS through Apache Knox. I need to be able to specify username/password to authenticate, is there a way to do that ?

Best,
Jerome

**Comment by mtth** [comment]
You can use clients' `session` argument to specify custom authentication schemes. For example, for basic username/password authentication:

```python
from hdfs import InsecureClient
from requests import Session
from requests.auth import HTTPBasicAuth

# Create the appropriate session expected by Knox
session = Session()
session.auth = HTTPBasicAuth('user', 'pass') # Or any other authentication scheme

# Wire it inside a client (other clients would work, for example TokenClient).
client = InsecureClient('http://host:port', user='hdfs_user', session=session)
```

I'm not familiar with Apache Knox so I'm not sure which authentication scheme you're expected to use. `requests` has many implementations though, so I suspect they'll have the one you need.
