### ISSUE TITLE
What is the correct name of this program

### ISSUE THREAD

**Issue by kerrywatson1** [mtth/hdfs#91]
You refer to it as Hdfs, HdfsCLI and hdfs 2.1.0. Which should I use to cite the correct name in text for users? 

Thanks in advance.

**Comment by mtth** [comment]
To help disambiguate it from the underlying [HDFS](https://hadoop.apache.org/docs/r1.2.1/hdfs_design.html) system, I usually refer to the project as HdfsCLI (e.g. in the [documentation](https://hdfscli.readthedocs.io/en/latest/)). [`hdfs`](https://pypi.python.org/pypi/hdfs) is the package's name on pypi; `hdfs-2.1.01` if you include the current latest version (dropping the suffix is somewhat similar to other projects, for example [Vue.js](https://vuejs.org/)' package is named [`vue`](https://www.npmjs.com/package/vue)).

Does this help clarify?

**Comment by kerrywatson1** [comment]
Thank you very much! That is exactly what I needed to know.
