### ISSUE TITLE
module 'fastavro' has no attribute '_writer'

### ISSUE THREAD

**Issue by SqySimmon** [mtth/hdfs#95]
AttributeError module 'fastavro' has no attribute '_writer' happens in hdfs/ext/avro/__init__.py ： 
`self._sync_interval = sync_interval or 1000 * fastavro._writer.SYNC_SIZE`

**Comment by seerwright** [comment]
Same issue for me. 
```
File "/usr/bin/anaconda3/envs/p3sci/lib/python3.6/site-packages/hdfs/ext/avro/__init__.py", line 264, in __init__
self._sync_interval = sync_interval or 1000 * fastavro._writer.SYNC_SIZE
AttributeError: module 'fastavro' has no attribute '_writer'
```

Imports:
```
from hdfs import InsecureClient
from hdfs import HdfsError
from hdfs.ext.dataframe import read_dataframe, write_dataframe
```

Calling write_dataframe:
`write_dataframe(client, 'johnf.avro', data_to_write)`

Package versions:
```
python-hdfs               2.1.0                    py36_0    conda-forge
fastavro                  0.17.9                   py36_1    conda-forge
```

**Comment by soares741** [comment]
I have the same problem and solved it the same way @marchbnr did

**Comment by mtth** [comment]
From `2.4.0` onwards, `hdfs` is compatible with the latest `fastavro` version (`0.21.19` currently).
