### ISSUE TITLE
 Failed to establish a new connection: [Errno -5] No address associated with hostname

### ISSUE THREAD

**Issue by Crackpot** [mtth/hdfs#98]
It successfully displays the list of files in my directory"/user/hive/warehouse":
['project1.db', 'project3.db', 'project4.db']

When I upload a file 'projects_info_files/project_4_csv_data.csv' to the target directory '/user/hive/warehouse/project4.db/order_detail_ext/project_4_csv_data.csv', it shows me:
<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd7b31d8a90>: Failed to establish a new connection: [Errno -5] No address associated with hostname

The following is my /etc/hosts configuration:
crackpot@thinkpad [19:34:14] [~]
-> % cat /etc/hosts|grep datawarehouse
172.17.0.3    datawarehouse

The following is my code：
hdfs_client = hdfs_Client("http://datawarehouse:50070")
print("查看hdfs中/user/hive/warehouse下面的文件{0}".format(hdfs_client.list('/user/hive/warehouse', status=False)))
print("上传'{0}'到'{1}'中".format(filename_csv_target, my_file))
hdfs_client.upload(my_file, filename_csv_target, cleanup=True)

**Comment by aqzjt** [comment]
No address associated with hostname      datawarehouse   in /etc/hosts   要绑定

**Comment by Crackpot** [comment]
cat /etc/hosts|grep datawarehouse
172.17.0.3 datawarehouse

**Comment by mtth** [comment]
Closing since this doesn't look like an HdfsCLI issue.
